version: '3.8'
services:
  db:
    container_name: mysql_container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "flaskapp"
      #poner el de nuestro proyecto
      MYSQL_ROOT_PASSWORD: "password"  
      
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: flask_web
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy  
    environment:
      DATABASE_URL: "mysql+pymysql://root:password@db/flaskapp"
